<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Piloto.Rules</RootNamespace>
    <AssemblyName>Piloto.Rules</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Piloto.Core\Piloto.Core.csproj" />
  </ItemGroup>

</Project>
